### ISSUE TITLE
[tube.ipynb] Is it necessary to mark the facets?

### ISSUE THREAD

**Issue by sbrisard** [solides-sorbonne/5ag07#2]
Cell 9 reads

```
facets = dolfin.MeshFunction('size_t', mesh, 1)
facets.set_all(0)
bottom.mark(facets, 1)
outer.mark(facets, 2)
left.mark(facets, 3)
inner.mark(facets, 4)
```

Markers are used in order to apply the loading (through `ds(2)` and `ds(4)`, see cell 17). Is it really necessary? Is there another way to get at the proper surface element through the functions `inner` and `outer` directly?

**Comment by cmaurini** [comment]
This is the good way currently in FEniCS. More efficiently, one can mark the facets in gmsh and import the meshfunction.
